# Exploratory Data Analysis

In [3]:
import pandas as pd
import numpy as np

In [4]:
# pull up data for EDA
heal_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_health_condition_v1.1.csv")
ownr_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_dog_owner_v1.1.csv")
cncr_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_cancer_condition_v1.1.csv")

# if in Google Colab:
# heal_df = pd.read_csv("/content/drive/Shared drives/CAPSTONE/CSV_DATA/DAP_2020_HLES_health_condition_v1.1.csv")
# ownr_df = pd.read_csv("/content/drive/Shared drives/CAPSTONE/CSV_DATA/DAP_2020_HLES_dog_owner_v1.1.csv")
# cncr_df = pd.read_csv("/content/drive/Shared drives/CAPSTONE/CSV_DATA/DAP_2020_HLES_cancer_condition_v1.1.csv")

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3257: DtypeWarning: Columns (119,121,123,125,127,136,167,195,241,242,243,244,245,246,247,248,256,376,520) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
# MINOR EDA
print(len(heal_df))
print(list(heal_df.columns))
heal_df.head(10)

77576
['dog_id', 'hs_condition', 'hs_condition_cause_other_description', 'hs_condition_is_congenital', 'hs_condition_other_description', 'hs_condition_type', 'hs_diagnosis_month', 'hs_diagnosis_year', 'hs_eye_condition_cause', 'hs_follow_up_ongoing', 'hs_neurological_condition_vestibular_disease_type', 'hs_required_surgery_or_hospitalization']

,dog_id,hs_condition,hs_condition_cause_other_description,hs_condition_is_congenital,hs_condition_other_description,hs_condition_type,hs_diagnosis_month,hs_diagnosis_year,hs_eye_condition_cause,hs_follow_up_ongoing,hs_neurological_condition_vestibular_disease_type,hs_required_surgery_or_hospitalization
0,68063,423.0,NaN,False,NaN,4,3.0,2016.0,NaN,True,NaN,4.0
1,68063,426.0,NaN,False,NaN,4,3.0,2016.0,NaN,True,NaN,4.0
2,68063,712.0,NaN,False,NaN,7,3.0,2016.0,NaN,False,NaN,4.0
3,68063,714.0,NaN,False,NaN,7,8.0,2016.0,NaN,True,NaN,4.0
4,68063,1617.0,NaN,False,NaN,16,2.0,2017.0,NaN,True,NaN,4.0
5,68063,1817.0,NaN,False,NaN,18,8.0,2019.0,NaN,True,NaN,4.0
6,54147,1215.0,NaN,False,NaN,12,3.0,2020.0,NaN,True,NaN,4.0
7,54147,1803.0,NaN,False,NaN,18,6.0,2018.0,NaN,False,NaN,4.0
8,43693,305.0,NaN,False,NaN,3,3.0,2018.0,NaN,False,NaN,4.0
9,43693,307.0,NaN,False,NaN,3,1.0,2020.0,NaN,True,NaN,4.0

In [6]:
# need to know how many records per dog
# going to handle each entry as a separate visit for now, 
# but it looks like it is an entry per disease, so should massage later
# When come back to this: assume that if same month and same year, 
# but different diseases, it was during the same visit
heal_df.groupby('dog_id').count()

,hs_condition,hs_condition_cause_other_description,hs_condition_is_congenital,hs_condition_other_description,hs_condition_type,hs_diagnosis_month,hs_diagnosis_year,hs_eye_condition_cause,hs_follow_up_ongoing,hs_neurological_condition_vestibular_disease_type,hs_required_surgery_or_hospitalization
dog_id,,,,,,,,,,,
3,3,0,3,0,3,3,3,0,3,0,3
6,1,0,1,0,1,1,1,0,1,0,1
9,5,0,5,2,5,5,5,0,5,0,5
11,3,0,3,0,3,3,3,1,3,0,3
13,1,0,1,0,1,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
92568,7,0,7,4,7,7,7,0,7,0,7
92582,4,0,4,0,4,4,4,0,4,0,4
92584,3,0,3,0,3,3,3,0,3,0,3
92592,1,0,1,0,1,1,1,0,1,0,1
92595,1,0,1,0,1,1,1,0,1,0,1

In [7]:
seq_length = 4
# reduce to just dogs with 4+ health records
# then look at the most common conditions & most common surgical/hospitalization scenarios
sm_hl_df = heal_df[['dog_id', 'hs_condition_type','hs_required_surgery_or_hospitalization']]
# sm_hl_df.groupby('hs_condition_type').count()
# reduce to only dogs with seq_lenth+ of records
segmin_df = sm_hl_df[sm_hl_df.groupby('dog_id')['dog_id'].transform('size') > seq_length]
print(len(segmin_df))
# most common conditions
segmin_df.groupby('hs_condition_type').count()
# most common are (in order):
# 4, 3, 18, 16, 11, 1, etc.
# skin - 4 - 4990
# mouth/dental/oral - 3 - 4837
# trauma - 18 - 3231
# infection/parasites - 16 - 3197
# bone/orthoepedic - 11 - 2837
# eye - 1 - 2170

40712

                   dog_id  hs_required_surgery_or_hospitalization
hs_condition_type
1                    2765                                    2752
2                    2215                                    2194
3                    6434                                    6420
4                    6384                                    6365
5                    1353                                    1339
6                     788                                     775
7                    2497                                    2364
8                     654                                     641
9                    1442                                    1437
10                    298                                     298
11                   3725                                    3720
12                    962                                     959
13                    609                                     609
14                    113                                     111
15                     96                                      96
16                   4296                                    4263
17                   1595                                    1574
18                   4354                                    4335
19                    132                                     130

In [8]:
# how many dogs got kicked - example of pulling out specific conditions
kicked = heal_df.loc[(heal_df['hs_condition']==1811),['dog_id', 'hs_condition_type','hs_required_surgery_or_hospitalization']]
kicked

       dog_id  hs_condition_type  hs_required_surgery_or_hospitalization
342     32832                 18                                     4.0
1029    84553                 18                                     4.0
1481    76775                 18                                     4.0
2028    62034                 18                                     4.0
2258    82174                 18                                     4.0
...       ...                ...                                     ...
74267   35175                 18                                     4.0
75395   17203                 18                                     4.0
76853   67329                 18                                     4.0
77221   74735                 18                                     2.0
77539   57871                 18                                     4.0

[99 rows x 3 columns]

In [9]:
# How many dogs have skin relation issues and what are they
skin = heal_df.loc[(heal_df['hs_condition_type']==4),['dog_id', 'hs_condition','hs_required_surgery_or_hospitalization']]
skin

       dog_id  hs_condition  hs_required_surgery_or_hospitalization
0       68063         423.0                                     4.0
1       68063         426.0                                     4.0
15      31102         410.0                                     4.0
19      87218         406.0                                     4.0
20      87218         428.0                                     1.0
...       ...           ...                                     ...
77543    2922         426.0                                     4.0
77551   79295         412.0                                     4.0
77552   79295         421.0                                     4.0
77553   79295         426.0                                     4.0
77565   69567         411.0                                     4.0

[11852 rows x 3 columns]

In [10]:
# break down of different skin conditions by type
skin.groupby('hs_condition').count()

              dog_id  hs_required_surgery_or_hospitalization
hs_condition
401.0              6                                       6
403.0             62                                      62
404.0            356                                     356
405.0            774                                     774
406.0            828                                     828
407.0            491                                     491
408.0            395                                     395
409.0             20                                      20
410.0            407                                     407
411.0            810                                     810
412.0            842                                     842
413.0             16                                      16
414.0            286                                     286
415.0            340                                     340
416.0              2                                       2
418.0              1                                       1
419.0             11                                      11
420.0              1                                       1
421.0             48                                      48
423.0           1164                                    1164
424.0            259                                     259
425.0            131                                     131
426.0           1878                                    1878
427.0             14                                      14
428.0            942                                     942
429.0             71                                      71
430.0            155                                     155
431.0              4                                       4
432.0            692                                     692
498.0            806                                     806

In [11]:
# just looking at skin issues - want it broken down by hospitalized, surgery, both, none
skin1_df = heal_df[['dog_id', 'hs_condition_type','hs_required_surgery_or_hospitalization']]
# sm_hl_df.groupby('hs_condition_type').count()
# reduce to only dogs with seq_lenth+ of records
# segmin_df = skin1_df[skin1_df.groupby('dog_id')['dog_id'].transform('size') > seq_length]
print(len(skin1_df))
skin2_df = skin1_df.loc[(skin1_df['hs_condition_type']==4),['dog_id', 'hs_condition_type','hs_required_surgery_or_hospitalization']]
# most common conditions
skin2_df.groupby('hs_required_surgery_or_hospitalization').count()

77576

                                        dog_id  hs_condition_type
hs_required_surgery_or_hospitalization
1.0                                        557                557
2.0                                         70                 70
3.0                                         42                 42
4.0                                      11143              11143

In [12]:
# most common surgical/hospitalization scenarios
segmin_df.groupby('hs_required_surgery_or_hospitalization').count()

                                        dog_id  hs_condition_type
hs_required_surgery_or_hospitalization
1.0                                       5680               5680
2.0                                       1807               1807
3.0                                       1746               1746
4.0                                      31149              31149

In [15]:
print(len(cncr_df))
print(list(cncr_df.columns))
cncr_df.head(10)

1751
['dog_id', 'hs_cancer_locations_adrenal_gland', 'hs_cancer_locations_anal_sac', 'hs_cancer_locations_bladder_or_urethra', 'hs_cancer_locations_blood', 'hs_cancer_locations_bone_or_joint', 'hs_cancer_locations_brain', 'hs_cancer_locations_cardiac_tissue', 'hs_cancer_locations_ear', 'hs_cancer_locations_esophagus', 'hs_cancer_locations_eye', 'hs_cancer_locations_gallbladder_or_bile_duct', 'hs_cancer_locations_gastrointestinal_tract', 'hs_cancer_locations_kidney', 'hs_cancer_locations_liver', 'hs_cancer_locations_lung', 'hs_cancer_locations_lymph_nodes', 'hs_cancer_locations_mammary_tissue', 'hs_cancer_locations_muscle_or_soft_tissue', 'hs_cancer_locations_nerve_sheath', 'hs_cancer_locations_nose_or_nasal_passage', 'hs_cancer_locations_oral_cavity', 'hs_cancer_locations_other', 'hs_cancer_locations_other_description', 'hs_cancer_locations_ovary_or_uterus', 'hs_cancer_locations_pancreas', 'hs_cancer_locations_perianal_area', 'hs_cancer_locations_pituitary_gland', 'hs_cancer_locations_prostate', 'hs_cancer_locations_rectum', 'hs_cancer_locations_skin_of_limb_or_foot', 'hs_cancer_locations_skin_of_trunk_body_head', 'hs_cancer_locations_spinal_cord', 'hs_cancer_locations_spleen', 'hs_cancer_locations_testicle', 'hs_cancer_locations_thyroid', 'hs_cancer_locations_unknown', 'hs_cancer_locations_venereal', 'hs_cancer_types_adenocarcinoma', 'hs_cancer_types_adenoma', 'hs_cancer_types_basal_cell_tumor', 'hs_cancer_types_carcinoma', 'hs_cancer_types_chondrosarcoma', 'hs_cancer_types_cystadenoma', 'hs_cancer_types_epidermoid_cyst', 'hs_cancer_types_epulides', 'hs_cancer_types_fibrosarcoma', 'hs_cancer_types_hemangioma', 'hs_cancer_types_hemangiosarcoma', 'hs_cancer_types_histiocytic_sarcoma', 'hs_cancer_types_histiocytoma', 'hs_cancer_types_insulinoma', 'hs_cancer_types_leiomyoma', 'hs_cancer_types_leiomyosarcoma', 'hs_cancer_types_leukemia', 'hs_cancer_types_lipoma', 'hs_cancer_types_lymphoma_lymphosarcoma', 'hs_cancer_types_mast_cell_tumor', 'hs_cancer_types_melanoma', 'hs_cancer_types_meningioma', 'hs_cancer_types_multiple_myeloma', 'hs_cancer_types_osteosarcoma', 'hs_cancer_types_other', 'hs_cancer_types_other_description', 'hs_cancer_types_papilloma', 'hs_cancer_types_peripheral_nerve_sheath_tumor', 'hs_cancer_types_plasmacytoma', 'hs_cancer_types_rhabdomyosarcoma', 'hs_cancer_types_sarcoma', 'hs_cancer_types_sebaceous_adenoma', 'hs_cancer_types_soft_tissue_sarcoma', 'hs_cancer_types_squamous_cell_carcinoma', 'hs_cancer_types_thymoma', 'hs_cancer_types_transitional_cell_carcinoma', 'hs_cancer_types_unknown', 'hs_follow_up_ongoing', 'hs_initial_diagnosis_month', 'hs_initial_diagnosis_year', 'hs_leukemia_types_acute', 'hs_leukemia_types_chronic', 'hs_leukemia_types_other', 'hs_leukemia_types_unknown', 'hs_lymphoma_lymphosarcoma_types_b_cell', 'hs_lymphoma_lymphosarcoma_types_other', 'hs_lymphoma_lymphosarcoma_types_other_description', 'hs_lymphoma_lymphosarcoma_types_t_cell', 'hs_lymphoma_lymphosarcoma_types_t_zone', 'hs_lymphoma_lymphosarcoma_types_unknown', 'hs_required_surgery_or_hospitalization']

,dog_id,hs_cancer_locations_adrenal_gland,hs_cancer_locations_anal_sac,hs_cancer_locations_bladder_or_urethra,hs_cancer_locations_blood,hs_cancer_locations_bone_or_joint,hs_cancer_locations_brain,hs_cancer_locations_cardiac_tissue,hs_cancer_locations_ear,hs_cancer_locations_esophagus,...,hs_leukemia_types_chronic,hs_leukemia_types_other,hs_leukemia_types_unknown,hs_lymphoma_lymphosarcoma_types_b_cell,hs_lymphoma_lymphosarcoma_types_other,hs_lymphoma_lymphosarcoma_types_other_description,hs_lymphoma_lymphosarcoma_types_t_cell,hs_lymphoma_lymphosarcoma_types_t_zone,hs_lymphoma_lymphosarcoma_types_unknown,hs_required_surgery_or_hospitalization
0,29702,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,86399,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,92031,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,39653,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2114,False,False,False,False,False,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
5,64276,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
6,43961,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
7,60796,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
8,90315,False,False,False,False,True,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
9,46085,False,False,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [14]:
print(len(ownr_df))
print(list(ownr_df.columns))
ownr_df.head(10)

27541

,owner_id,oc_household_adult_count,oc_household_child_count,oc_household_person_count,oc_primary_residence_census_division,oc_primary_residence_ownership,oc_primary_residence_ownership_other_description,oc_primary_residence_state,oc_primary_residence_time_percentage,oc_secondary_residence,...,pa_swim_locations_other_description,pa_swim_locations_pond_or_lake,pa_swim_locations_river_stream_or_creek,pa_swim_locations_swimming_pool,pa_swim_moderate_weather_frequency,ss_vet_frequency,st_hles_completion_date,st_portal_account_creation_date,st_portal_invitation_date,st_vip_or_staff
0,1,2,0,2,9.0,2,NaN,WA,5.0,True,...,NaN,NaN,NaN,NaN,NaN,2,2019-12-31,2019-12-30,2019-12-30,1
1,2,2,0,2,9.0,2,NaN,WA,NaN,False,...,NaN,NaN,NaN,NaN,NaN,2,2020-01-05,2020-01-04,2019-12-30,1
2,3,2,0,2,9.0,2,NaN,WA,NaN,False,...,NaN,NaN,NaN,NaN,NaN,2,2020-04-01,2020-03-23,2020-03-23,0
3,4,2,0,2,5.0,2,NaN,VA,NaN,False,...,NaN,NaN,NaN,NaN,NaN,2,2020-03-29,2020-03-24,2020-03-23,0
4,5,2,1,3,7.0,2,NaN,TX,NaN,False,...,NaN,NaN,NaN,NaN,NaN,3,2020-01-27,2020-01-27,2019-12-30,1
5,6,2,0,2,5.0,2,NaN,NC,5.0,True,...,NaN,NaN,NaN,NaN,NaN,3,2020-03-23,2020-03-23,2020-03-23,0
6,7,2,0,2,9.0,2,NaN,WA,4.0,True,...,NaN,NaN,NaN,NaN,NaN,3,2020-01-15,2020-01-15,2019-12-30,1
7,8,2,0,2,8.0,2,NaN,NV,NaN,False,...,NaN,True,False,True,5.0,3,2020-05-04,2020-04-04,2020-03-23,0
8,9,2,0,2,4.0,2,NaN,IA,5.0,True,...,NaN,NaN,NaN,NaN,NaN,2,2020-04-22,2020-03-23,2020-03-23,0
9,10,1,0,1,3.0,2,NaN,WI,NaN,False,...,NaN,NaN,NaN,NaN,NaN,3,2020-04-16,2020-04-13,2020-03-23,0

### Features currently included:
STATIC (from owner dataset):\
‘dog_id’ - for joining with health conditions dataset

CATEGORIES:
1. GENERAL HEALTH
2. EXCITABILITY
3. AGGRESSION
4. FEAR AND ANXIETY
5. SEPARATION-RELATED BEHAVIOR
6. ATTACHMENT, ATTENTION SEEKING
7. TRAINING DIFFICULTY
8. MISCELLANEOUS BEHAVIORS
9. DOGGO DEMOGRAPHICS-BREED
10. OTHER DEMOGRAPHICS
11. ENVIRONMENTAL
12. LIFESTYLE
13. MEDICATIONS / PREVENTIVES
14. TEMPORAL

GENERAL HEALTH\
[‘hs_general_health','Hs_recent_hospitalization']
- ‘hs_general_health' - 1 (Excellent) - 6 (Very poor)
- 'hs_recent_hospitalization' - true/false

EXCITABILITY\
['db_excitement_level_before_car_ride','db_excitement_level_before_walk']
- 'db_excitement_level_before_car_ride',  0.0 (calm) - 4.0 (extremely excitable)
- 'db_excitement_level_before_walk', 0.0 (calm) - 4.0 (extremely excitable)

AGGRESSION\
['db_aggression_level_approached_while_eating','db_aggression_level_delivery_workers_at_home','db_aggression_level_food_taken_away','db_aggression_level_on_leash_unknown_dog','db_aggression_level_on_leash_unknown_human', 'db_aggression_level_toys_taken_away','db_aggression_level_unknown_aggressive_dog', 'db_aggression_level_unknown_human_near_yard']
- 'db_aggression_level_approached_while_eating', 0.0 (none) - 4.0 (serious)
- 'db_aggression_level_delivery_workers_at_home', 0.0 (none) - 4.0 (serious)
- 'db_aggression_level_food_taken_away',  0.0 (none) - 4.0 (serious)
- 'db_aggression_level_on_leash_unknown_dog',  0.0 (none) - 4.0 (serious)
- 'db_aggression_level_on_leash_unknown_human',  0.0 (none) - 4.0 (serious)
- 'db_aggression_level_toys_taken_away',  0.0 (none) - 4.0 (serious)
- 'db_aggression_level_unknown_aggressive_dog',  0.0 (none) - 4.0 (serious)
- 'db_aggression_level_unknown_human_near_yard',  0.0 (none) - 4.0 (serious)

FEAR AND ANXIETY\
['db_fear_level_bathed_at_home','db_fear_level_loud_noises','db_fear_level_nails_clipped_at_home','db_fear_level_unknown_aggressive_dog','db_fear_level_unknown_dogs','db_fear_level_unknown_human_away_from_home','db_fear_level_unknown_human_touch','db_fear_level_unknown_objects_outside','db_fear_level_unknown_situations']
- 'db_fear_level_bathed_at_home',  0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_loud_noises',  0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_nails_clipped_at_home',   0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_aggressive_dog',  0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_dogs',  0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_human_away_from_home',   0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_human_touch',   0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_objects_outside',  0.0 (none) - 4.0 (extreme fear)
- 'db_fear_level_unknown_situations',  0.0 (none) - 4.0 (extreme fear)

SEPARATION-RELATED BEHAVIOR\
['db_left_alone_barking_frequency','db_left_alone_restlessness_frequency','db_left_alone_scratching_frequency']
- 'db_left_alone_barking_frequency',  0.0 (never) - 4.0 (always)
- 'db_left_alone_restlessness_frequency',  0.0 (never) - 4.0 (always)
- 'db_left_alone_scratching_frequency',  0.0 (never) - 4.0 (always)

ATTACHMENT, ATTENTION SEEKING\
['db_attention_seeking_follows_humans_frequency','db_attention_seeking_sits_close_to_humans_frequency']
- 'db_attention_seeking_follows_humans_frequency', 0.0 (never) - 4.0 (always)
- 'db_attention_seeking_sits_close_to_humans_frequency',  0.0 (never) - 4.0 (always)

TRAINING DIFFICULTY\
['db_training_distraction_frequency','db_training_obeys_sit_command_frequency','db_training_obeys_stay_command_frequency']
- 'db_training_distraction_frequency',  0.0 (never) - 4.0 (always)
- 'db_training_obeys_sit_command_frequency',  0.0 (never) - 4.0 (always)
- 'db_training_obeys_stay_command_frequency',  0.0 (never) - 4.0 (always)

MISCELLANEOUS BEHAVIORS\
['db_barks_frequency','db_chases_birds_frequency','db_chases_squirrels_frequency','db_chases_tail_frequency','db_chews_inappropriate_objects_frequency','db_defecates_alone_frequency','db_energetic_frequency','db_escapes_home_or_property_frequency','db_hyperactive_frequency','db_playful_frequency','db_pulls_leash_frequency','db_urinates_alone_frequency','db_urinates_in_home_frequency']
- 'db_barks_frequency', 0.0 (never) - 4.0 (always)
- 'db_chases_birds_frequency', 0.0 (never) - 4.0 (always)
- 'db_chases_squirrels_frequency', 0.0 (never) - 4.0 (always)
- 'db_chases_tail_frequency', 0.0 (never) - 4.0 (always)
- 'db_chews_inappropriate_objects_frequency',  0.0 (never) - 4.0 (always)
- 'db_defecates_alone_frequency',  0.0 (never) - 4.0 (always)
- 'db_energetic_frequency',  0.0 (never) - 4.0 (always)
- 'db_escapes_home_or_property_frequency',  0.0 (never) - 4.0 (always)
- 'db_hyperactive_frequency',   0.0 (never) - 4.0 (always)
- 'db_playful_frequency',   0.0 (never) - 4.0 (always)
- 'db_pulls_leash_frequency',   0.0 (never) - 4.0 (always)
- 'db_urinates_alone_frequency',   0.0 (never) - 4.0 (always)
- 'db_urinates_in_home_frequency'  0.0 (never) - 4.0 (always)

DOGGO DEMOGRAPHICS\ 
BREED (# representing a breed)\
['dd_breed_pure_or_mixed', 'dd_combined_main_breed']
- 'dd_breed_pure_or_mixed', 1 (purebred) 2 (mixed)
- 'dd_combined_main_breed', categorical # for breed - combines these two:
- - 'dd_breed_pure', categorical for breed, only when dog is purebred
- - 'dd_breed_pure_non_akc', categorical for breed, only when dog is purebred and isn't in the breed_pure list
- - 'dd_breed_mixed_primary', categorical for breed, only when dog is mixed

OTHER DEMOGRAPHICS\
['dd_age_years','dd_spayed_or_neutered','dd_spay_or_neuter_age','dd_insurance','dd_sex','dd_weight_lbs','dd_weight_range']
- 'dd_age_years' - 0.000 - 30.000 - take out all dogs with zero, since still growing/puppies
- 'dd_spayed_or_neutered', 1 YES 2 NO, but look out for NaN
- 'dd_spay_or_neuter_age', 1 (<6 mo), 2 (6-12mo), 3 (12-18mo), 4 (18-24mo), 5 (2-4yr), 6(4-6yr), 7(6-8yr), 8 (8+yr), 99(unknown)
- 'dd_insurance' - true/false
- 'dd_sex', 1 (M) 2(F)
- 'dd_weight_lbs', 0.0 - 150.0 (cotinuous)
- 'dd_weight_range' YES, need to get values for range? (categorical)
1- 0‐10 lbs\
2 - 11‐20 lbs\
3 - 21‐30 lbs\
4 - 31‐40 lbs\
5 - 41‐50 lbs\
6 - 51‐60 lbs\
7 - 61‐70 lbs\
8 - 71‐80 lbs\
9 - 81‐90 lbs\
10 - 91‐100 lbs\
11 - More than 100 lbs

ENVIRONMENTAL\
['de_air_cleaner_present','de_air_freshener_present','de_asbestos_present','de_central_air_conditioning_present','de_central_heat_present','de_routine_toys','de_daytime_sleep_avg_hours','de_nighttime_sleep_avg_hours','de_eats_feces','de_eats_grass_frequency','de_interacts_with_neighborhood_animals''de_interacts_with_neighborhood_humans','de_licks_chews_or_plays_with_non_toys']
- 'de_air_cleaner_present', 'de_air_freshener_present', 'de_asbestos_present', 'de_central_air_conditioning_present', 'de_central_heat_present', ALL, 1 YES, 0 NO, 99 UNKNOWN
- 'de_routine_toys' - 1 YES, 0 NO
- 'de_daytime_sleep_avg_hours', 0-24, 99 means unknown
- 'de_nighttime_sleep_avg_hours' 0-24, 99 means unknown
- 'de_eats_feces', 1 YES 0 NO 99 UNKNOWN
- 'de_eats_grass_frequency', 1 (frequently), 2 (infrequently), 0 (never)
- 'de_interacts_with_neighborhood_animals', 1 YES 0 NO
- 'de_interacts_with_neighborhood_humans', 1 YES 0 NO
- 'de_licks_chews_or_plays_with_non_toys', 1 YES 0 NO

LIFESTYLE\
['df_appetite','df_appetite_change_last_year','df_ever_malnourished','df_ever_overweight','df_ever_underweight','df_feedings_per_day','free_fed','df_diet_consistency','df_primary_diet_component''df_treats_frequency','df_weight_change_last_year']
- 'df_appetite',  1 (poor) 2 (avg) 3 (voracious)
- 'df_appetite_change_last_year', 1 YES 0 NO 99 UNKNOWN
- 'df_ever_malnourished', 1 YES 0 NO 99 UNKNOWN
- 'df_ever_overweight', 1 YES 0 NO 99 UNKNOWN
- 'df_ever_underweight', 1 YES 0 NO 99 UNKNOWN
- 'df_feedings_per_day', 1 (ONCE) 2 (TWICE) 3 (3+) 4 (Free fed) -> breakout free fed as separate data point 'free_fed'
- 'df_diet_consistency', 1 (very consistent) 2 (somewhat consistent) 3 not at all consistent) 98 OTHER
- 'df_treats_frequency', 3 (3+/day) 2 (2X) 1 (1X) 4 (occasionally, not daily) 0 never
- 'df_weight_change_last_year' 1 YES 0 NO 3 (dog is puppy still growing) 99 UNKNOWN
- 'df_primary_diet_component':\
1 - Commercially prepared dry food (kibble)\
2 - Commercially prepared canned food\
3 - Commercially prepared freeze‐dried food\
4 - Commercially prepared refrigerated or frozen raw food\
5 - Commercially prepared semi‐dry or semi‐moist food\
6 - Home prepared cooked diet\
7 - Home prepared raw diet\
98 - Other

MEDICATIONS / PREVENTIVES\
['mp_dental_examination_frequency','mp_dental_brushing_frequency','mp_dental_treat_frequency','mp_dental_food_frequency','mp_dental_breath_freshener_frequency','mp_flea_and_tick_treatment','mp_heartworm_preventative']
- 'mp_dental_examination_frequency', 0 (never) 1 (occasionally) 2 (monthly) 3 (weekly) 4 (daily)
- 'mp_dental_brushing_frequency', 0 (never) 1 (occasionally) 2 (monthly) 3 (weekly) 4 (daily)
- 'mp_dental_treat_frequency', 0 (never) 1 (occasionally) 2 (monthly) 3 (weekly) 4 (daily)
- 'mp_dental_food_frequency', 0 (never) 1 (occasionally) 2 (monthly) 3 (weekly) 4 (daily)
- 'mp_dental_breath_freshener_frequency', 0 (never) 1 (occasi) 2 (monthly) 3 (weekly) 4 (daily)
- 'mp_flea_and_tick_treatment', t/f
- 'mp_heartworm_preventative', t/f

TEMPORAL: (comes from health_conditions dataset)\
[‘dog_id’,‘hs_diagnosis_month’,‘hs_diagnosis_year’,‘hs_follow_up_ongoing',‘hs_required_surgery_or_hospitalization’]\
The main temporal data point is the condition that is diagnosis, which is basically data leakage, because it accounts for the diseases that will be predicted in the analysis.\
only have these available:
- ‘Dog_id’ -> to join to owner table
- ‘hs_diagnosis_month’	-> for reference
- ‘hs_diagnosis_year’ -> for reference
- ‘hs_follow_up_ongoing -> t/f
- ‘hs_required_surgery_or_hospitalization’ -> 1 (surgery) 2 (hospital) 3 (both) 4 (none)


### Features to predict:
['hs_health_conditions_skin','hs_health_conditions_eye','hs_health_conditions_cancer']

- 'hs_health_conditions_skin', 1 YES, 0 NO 
- 'hs_health_conditions_eye',  1 YES, 0 NO
- 'hs_health_conditions_cancer' -  1 YES, 0 NO (is actually 2 for yes)